### ISSUE TITLE
Incident Reviews

### ISSUE THREAD

**Issue by chefsale** [near/community#14]
In cases where there is an issue with either: Mainnet, Testnet, Betanet or Devnet we have to have a incident review meeting in place.

This issue is created for the discussion about that. cc: @ilblackdragon @damons @vgrichina @SkidanovAlex @bowenwang1996 @ailisp @frol.

**Comment by chefsale** [comment]
I propose:

1. making this a public meeting where validators can join. 
2. It should be a weekly meeting which can be cancelled in case there is not enough to discuss.
3. Postmortems can be tracked in this repo under incidents folder.
4. We should create an issue for every incident and link it in the postmortem.

Let me know if this makes sense to you and any other feedback is more than welcome.

**Comment by ilblackdragon** [comment]
How about merging it with general validators meeting then (that we don't have right now, but should)?

**Comment by chefsale** [comment]
Hmm, that could be an option, only concern is time wise. Will there be enough time to cover everything in that meeting?

**Comment by frol** [comment]
Let's give it a try: /cc @near/nearcore-incidents

**Comment by bowenwang1996** [comment]
@chefsale @ilblackdragon I see no reasons to merge things together. Also I am not entirely sure whether this meeting needs to be public: for mainnet incidents for sure it should be, but for betanet incidents for example, I don't see us wasting people's time if it is purely caused by some internal mistake. Also I don't think we need a weekly meeting to discuss this (unless we are so pessimistic that we think that will be a major incident every week) and it should only happen when there is an incident (otherwise what are we even reviewing?).
